# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Getting blue fingers
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "" # the subpath of the site
url: "https://www.robinkoetsier.nl" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-175572271-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog
    - name: External

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: e-mail me!
      link: mailto:robinkoetsier@gmail.com

  follow:
    - name: Twitter
      link: http://twitter.com/RobinWilhelmus
      username: "@RobinWilhelmus"
    - name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/RobinKoetsier
      

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 2
